# Generated by Django 3.0.5 on 2020-04-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_mes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
