# Generated by Django 3.0.5 on 2020-04-23 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0002_parametro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movrotativo',
            options={'verbose_name': 'Movimento Rotativo'},
        ),
        migrations.AlterModelOptions(
            name='parametro',
            options={'verbose_name': 'Parâmetro'},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'verbose_name': 'Veículo'},
        ),
        migrations.CreateModel(
            name='Mensalista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamento.Veiculo')),
            ],
        ),
    ]
