# Generated by Django 3.0.5 on 2020-04-23 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0004_movmensalista'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movmensalista',
            options={'verbose_name': 'Movimento Mensalista'},
        ),
    ]
